rezerwacja_nip/rezerwacja_nip/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import path
from rezerwacja_nip_app import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('admin/login/', views.admin_login, name='admin_login'),
    path('register_nip/', views.register_nip, name='register_nip'),
    path('user_nip_list/', views.user_nip_list, name='user_nip_list'),
    path('admin-nip-list/', views.admin_nip_list, name='admin_nip_list'),
    path('login/', views.login_view, name='login_view'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('import_records/', views.import_records, name='import_records'),
    path('export_records/', views.export_records, name='export_records'),
    path('admin/update_expiration_days/<int:record_id>/', views.update_expiration_days, name='update_expiration_days'),


]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rezerwacja_nip/rezerwacja_nip_app/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import BaseValidator
from django.contrib import messages
from django.utils.deconstruct import deconstructible
from django.utils.translation import gettext_lazy as _


def validate_ten_digit_nip(value):
    if len(str(value)) != 10:
        raise ValidationError(_('NIP must be a 10-digit number.'), code='invalid_nip')

def validate_nine_digit_phone(value):
    if len(str(value)) != 9:
        raise ValidationError(_('Numer telefonu musi mieć dziewięć cyfr'), code='invalid_numer_telefonu')

class NIPRegistrationForm(forms.Form):
    email = forms.EmailField(label='email_uzytkownika')
    nip = forms.IntegerField(
        validators=[validate_ten_digit_nip],
        label='NIP'
    )
    nazwa= forms.CharField(label='nazwa',required=False)
    numer_telefonu_klienta= forms.IntegerField(
        validators=[validate_nine_digit_phone],
        label='Numer telefonu klienta',
        required=False
    )

    def clean(self):
        cleaned_data = super().clean()
        cleaned_data.get('nazwa')
        cleaned_data.get('numer_telefonu_klienta')
        return cleaned_data

    def dataEmailNip(self):
        data=super()
        data.get('email')
        data.get('nip')
        return data


class AdminLoginForm(forms.Form):
    username = forms.CharField(label='Username')
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

class NIPRecordImportForm(forms.Form):
    file = forms.FileField()

    def clean_file(self):
        file = self.cleaned_data['file']
        if not file.name.endswith('.xlsx'):
            raise ValidationError('Należy załadować plik Excela (rozszerzenie .xlsx).')
        return file

rezerwacja_nip/templates/admin_login.html
<!doctype html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Logowanie</title>
</head>
<body>
{% block content %}
<h1>Logowanie Administratora</h1>
<form method="post">
    {% csrf_token %}
    {{ login_form.as_p }}
    <button type="submit">Zaloguj</button>
</form>
{% endblock %}
</body>
</html>

rezerwacja_nip/templates/admin_nip_list.html
<!doctype html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<style>
    body {
    background-color: #f0f0f0; /* Kolor tła */
    font-family: Arial, sans-serif; /* Czcionka */
    margin: 0;
    padding: 0;
}

    .registration-form-container {
    max-width: 400px;
    margin: 0 auto;
    padding: 20px;
    border: 1px solid #ccc;
    border-radius: 5px;
    background-color: #fff;
}

/* Styl dla nagłówka formularza */
.registration-header {
    font-size: 24px;
    text-align: center;
    margin-bottom: 20px;
}

/* Styl dla formularza */
.registration-form {
    display: flex;
    flex-direction: column;
}

/* Styl dla przycisku rejestracji */
.registration-button {
    background-color: #007bff;
    color: #fff;
    border: none;
    padding: 10px 20px;
    margin-top: 10px;
    cursor: pointer;
    border-radius: 5px;
}

/* Styl dla komunikatów błędów */
.messages {
    list-style-type: none;
    padding: 0;
    margin-top: 10px;
}

.messages li {
    padding: 5px;
}

.error {
    color: #f00;
}
</style>
<body>
{% block content %}
    <h1>Lista wszystkich numerów NIP</h1>

    <table>
        <thead>
            <tr>
                <th>NIP</th>
                <th>Status</th>
                <th>Rezerwacja od</th>
                <th>Ważny do</th>
            </tr>
        </thead>
        <tbody>
            {% for nip in all_nips %}
                <tr>
                    <td>{{ nip.nip }}</td>
                    <td>{{ nip.current_status }}</td>
                    <td>{{ nip.reservation_date }}</td>
                    <td>{{ nip.expiration_date }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}
</body>
</html>

rezerwacja_nip/templates/admin_panel.html
<!doctype html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Panel Administratora</title>
</head>
<body>
{% block content %}
    <h1>Panel Administratora</h1>
    <table>
        <thead>
            <tr>
                <th>NIP</th>
                <th>Email</th>
                <th>Status</th>
                <th>Rezerwacja Wygasa</th>
            </tr>
        </thead>
        <tbody>
            <form method="post">
                {% csrf_token %}
                {% for record in records %}
                <tr>
                    <td>{{ record.nip }}</td>
                    <td><input type="text" name="email_{{ record.id }}" value="{{ record.email }}"></td>
                    <td><input type="text" name="status_{{ record.id }}" value="{{ record.status }}"></td>
                    <td><input type="text" name="expiration_{{ record.id }}" value="{{ record.expiration }}"></td>
                </tr>
                {% endfor %}
                <tr>
                    <td colspan="4"><button type="submit">Zapisz zmiany</button></td>
                </tr>
            </form>
            <form method="post" action="{% url 'import_records' %}">
                {% csrf_token %}
                <button type="submit" name="import-records" value="Import">Import</button>
            </form>
            <form method="post" action="{% url 'export_records' %}">
                {% csrf_token %}
                <button type="submit" name="export-records" value="Export">Export</button>
            </form>
        </tbody>
    </table>

    <h2>Email Addresses</h2>
    <form method="post">
        {% csrf_token %}
        <table>
            <thead>
                <tr>
                    <th>Email Address</th>
                </tr>
            </thead>
            <tbody>
                {% for email in emails %}
                <tr>
                    <td><input type="email" name="email_{{ email.id }}" value="{{ email.email }}"></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <button type="submit">Save Changes</button>
    </form>
{% endblock %}
</body>
</html>

rezerwacja_nip/templates/home.html
{%  load static %}
<!doctype html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Rezerwacja NIP</title>
</head>
<style>
    body {
    background-color: #f0f0f0; /* Kolor tła */
    font-family: Arial, sans-serif; /* Czcionka */
    margin: 0;
    padding: 0;
}

    .registration-form-container {
    max-width: 400px;
    margin: 0 auto;
    padding: 20px;
    border: 1px solid #ccc;
    border-radius: 5px;
    background-color: #fff;
}

/* Styl dla nagłówka formularza */
.registration-header {
    font-size: 24px;
    text-align: center;
    margin-bottom: 20px;
}

/* Styl dla formularza */
.registration-form {
    display: flex;
    flex-direction: column;
}

/* Styl dla przycisku rejestracji */
.registration-button {
    background-color: #007bff;
    color: #fff;
    border: none;
    padding: 10px 20px;
    margin-top: 10px;
    cursor: pointer;
    border-radius: 5px;
}

/* Styl dla komunikatów błędów */
.messages {
    list-style-type: none;
    padding: 0;
    margin-top: 10px;
}

.messages li {
    padding: 5px;
}

.error {
    color: #f00;
}
</style>
<body>

    <img src="../resources/elomoto.eco-logo-final.png" alt="Company Logo">
{% block content %}
    <h1>Strona główna</h1>
    {% if user.is_authenticated %}
        {% if user.is_staff %}
            <a href="/admin/">Panel Administratora</a>
        {% endif %}
        <p>Zalogowano jako: {{ user.username }}</p>
        <a href="{% url 'logout' %}">Wyloguj</a>
    {% else %}
        <p>Nie jesteś zalogowany.</p>
        <a href="{% url 'login' %}">Zaloguj</a>
    {% endif %}
{% endblock %}
{#{% block content %}#}
{#    <div class="registration-form-container">#}
{#        <h1 class="registration-header">Rejestracja NIP</h1>#}
{##}
{#        {% if messages %}#}
{#            <ul class="messages">#}
{#                {% for message in messages %}#}
{#                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>#}
{#                {% endfor %}#}
{#            </ul>#}
{#        {% endif %}#}
{##}
{#        <form class="registration-form" method="post" action="{% url 'register_nip' %}">#}
{#            {% csrf_token %}#}
{#            {{ registration_form.as_p }}#}
{#            <button class="registration-button" type="submit">Zarejestruj NIP</button>#}
{#        </form>#}
{#    </div>#}
{#{% endblock %}#}
</body>
</html>

rezerwacja_nip/templates/login.html
<!doctype html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<style>
    /* Add this CSS code to your styles.css file or create a new CSS file */

body {
  font-family: Arial, sans-serif;
  background-color: #f2f2f2;
  margin: 0;
  padding: 0;
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100vh;
}

.login-container {
  background-color: #fff;
  border-radius: 5px;
  box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
  padding: 20px;
  width: 300px;
  text-align: center;
}

.login-container h1 {
  font-size: 24px;
  margin-bottom: 20px;
}

.login-form {
  text-align: left;
}

.login-form label {
  display: block;
  margin-bottom: 8px;
  font-weight: bold;
}

.login-form input[type="text"],
.login-form input[type="password"] {
  width: 95%;
  padding: 10px;
  margin-bottom: 20px;
  border: 1px solid #ccc;
  border-radius: 3px;
  font-size: 16px;
}

.login-form button {
  background-color: #007bff;
  color: #fff;
  border: none;
  padding: 10px 20px;
  font-size: 18px;
  cursor: pointer;
  border-radius: 3px;
}

.login-form button:hover {
  background-color: #0056b3;
}

.error-message {
  color: red;
  margin-top: 10px;
}

/* Additional styles can be added as needed */

</style>
<body>
{% block content %}
    <div class="login-container">
    <h1>Logowanie</h1>

    {% if error_message %}
        <p>{{ error_message }}</p>
    {% endif %}

    <form method="post" class="login-form">
        {% csrf_token %}
        {{ login_form.as_p }}
        <button type="submit">Zaloguj</button>
    </form>
    </div>
{% endblock %}
</body>
</html>

rezerwacja_nip/templates/new_static_page.html
<!-- new_static_page.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>New Static Page</title>
</head>
<body>
    <h1>Welcome to the New Static Page</h1>
    <p>This is a new static page under the REZERWACJA_NIP_APP section.</p>
</body>
</html>

rezerwacja_nip/templates/register_nip.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<style>
    body {
    background-color: #f0f0f0; /* Kolor tła */
    font-family: Arial, sans-serif; /* Czcionka */
    margin: 0;
    padding: 0;
}

    .registration-form-container {
    max-width: 400px;
    margin: 0 auto;
    padding: 20px;
    border: 1px solid #ccc;
    border-radius: 5px;
    background-color: #fff;
}

/* Styl dla nagłówka formularza */
.registration-header {
    font-size: 24px;
    text-align: center;
    margin-bottom: 20px;
}

/* Styl dla formularza */
.registration-form {
    display: flex;
    flex-direction: column;
}

/* Styl dla przycisku rejestracji */
.registration-button {
    background-color: #007bff;
    color: #fff;
    border: none;
    padding: 10px 20px;
    margin-top: 10px;
    cursor: pointer;
    border-radius: 5px;
}

/* Styl dla komunikatów błędów */
.messages {
    list-style-type: none;
    padding: 0;
    margin-top: 10px;
}

.messages li {
    padding: 5px;
}

.error {
    color: #f00;
}
</style>
<body>
 {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
 {% endif %}
 <div id="logo">
    <img src="../resources/elomoto.eco-logo-final.png" alt="Company Logo" id="img">
 </div>
<!---<form method="post" action="{% url 'register_nip' %}" class="registration-form">-->
    {% csrf_token %}
    <label for="{{ registration_form.email.id_for_label }}">Email:</label>
    {{ registration_form.email }}
    <label for="{{ registration_form.nip.id_for_label }}">NIP:</label>
    {{ registration_form.nip }}
    <label for="{{ registration_form.nazwa.id_for_label }}">Nazwa:</label>
    {{ registration_form.nazwa }}
    <label for="{{ registration_form.numer_telefonu_klienta.id_for_label }}">Numer telefonu klienta:</label>
    {{ registration_form.numer_telefonu_klienta }}
    <button>Register</button>
<!---</form>-->
<a href="{% url 'home' %}">Powrót</a>

</body>
</html>

rezerwacja_nip/templates/registration_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Rejestracja</title>
</head>
<style>
    body {
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        height: 100vh;
        margin: 0;
        background-color: #f0f0f0;
        font-family: Arial, sans-serif;
        padding: 0;
    }

    .registration-form-container {
        display: flex;
        flex-direction: column;
        align-items: center;
        max-width: 400px;
        /* ... other styles ... */
    }

    /* Style labels */
    .registration-form label {
        font-weight: bold;
        margin-bottom: 5px;
    }

    /* Set a fixed width for input fields */
    .registration-form input[type="text"],
    .registration-form input[type="email"] {
        width: 100%;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
        margin-bottom: 10px;
    }

    /* Style the submit button */
    .registration-form button[type="submit"] {
        background-color: #007bff;
        color: #fff;
        border: none;
        padding: 10px 20px;
        margin-top: 10px;
        cursor: pointer;
        border-radius: 5px;
    }

    /* Style the error messages */
    .messages {
        list-style-type: none;
        padding: 0;
        margin-top: 10px;
    }

    .messages li {
        padding: 5px;
        color: #f00;
    }

    #img {
        width: 20%;
        margin-bottom: 20px; /* Add margin to separate the logo from the form */
    }
</style>
<body>
<div id="logo">
    <img src="../resources/elomoto.eco-logo-final.png" alt="Company Logo" id="img">
</div>
<div class="registration-form-container">
    {% if messages %}
      <ul class="messages">
         {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
      </ul>
    {% endif %}
    <!-- Your form elements and content go here -->
    <form method="post" action=" " class="registration-form">
        {% csrf_token %}
        <p><label for="id_email">Email:</label> <input type="email" name="email" id="id_email"></p>
        <p><label for="id_nip">NIP:</label> <input type="text" name="nip" id="id_nip"></p>
        <p><label for="id_nazwa">Nazwa:</label> <input type="text" name="nazwa" id="id_nazwa"></p>
        <p><label for="id_numer_telefonu_klienta">Numer telefonu klienta:</label> <input type="text" name="numer_telefonu_klienta" id="id_numer_telefonu_klienta"></p>
        <button type="submit">Register</button>
    </form>
    <a href="/user_nip_list">Powrót</a>
</div>
</body>
</html>

rezerwacja_nip/templates/user_nip_list.html
{%  load static %}
<!doctype html>
<html lang=pl>
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.js"></script>

    <title>Document</title>
</head>
<style>
body {
    background-color: #f0f0f0; /* Kolor tła */
    font-family: Arial, sans-serif; /* Czcionka */
    margin: 0;
    padding: 0;
}

    .registration-form-container {
    max-width: 400px;
    margin: 0 auto;
    padding: 20px;
    border: 1px solid #ccc;
    border-radius: 5px;
    background-color: #fff;
}

/* Styl dla nagłówka formularza */
.registration-header {
    font-size: 24px;
    text-align: center;
    margin-bottom: 20px;
}

/* Styl dla formularza */
.registration-form {
    display: flex;
    flex-direction: column;
}

/* Styl dla przycisku rejestracji */
.registration-button {
    background-color: #007bff;
    color: #fff;
    border: none;
    padding: 10px 20px;
    margin-top: 10px;
    cursor: pointer;
    border-radius: 5px;
}

/* Styl dla komunikatów błędów */
.messages {
    list-style-type: none;
    padding: 0;
    margin-top: 10px;
}

.messages li {
    padding: 5px;
}

.error {
    color: #f00;
}

.logout-button {
    background-color: #FF5733; /* Kolor tła */
    color: #fff; /* Kolor tekstu */
    border: none;
    padding: 10px 20px;
    margin-top: 10px;
    cursor: pointer;
    border-radius: 5px;
}

/* Styl dla przycisku wylogowania po najechaniu myszką */
.logout-button:hover {
    background-color: #E54E2E; /* Kolor tła po najechaniu myszką */
}

#logo{
    height:20%;
    width:20%;
    float:left;
}
#img{
    width:100%;
}
#rejestracja{
    width:80%;

}
 #lista {
    width: 80%;
    margin: 20px auto; /* Center the table with some top margin */
}

#lista table {
    width: 100%;
    border-collapse: collapse;
    margin-top: 20px;

}

#lista th, #lista td {
    border: 1px solid #ddd;
    padding: 12px; /* Increase padding for more spacing */
    text-align: left;
}

#lista th {
    background-color: #f2f2f2;
}

.dataTables_wrapper {
    position: relative;
    clear: both;
    zoom: 1;
}

.dataTables_filter {
    float: right;
    margin-bottom: 10px;
}

.dataTables_length {
    margin-top: 10px;
}

#nipTable_paginate {
    text-align: center;
    margin-top: 20px;
}

#nipTable_paginate span.current {
    background-color: #007bff;
    color: #fff;
    padding: 5px 10px;
    border-radius: 3px;
    margin: 0 5px;
}

#nipTable_paginate a {
    padding: 5px 10px;
    margin: 0 5px;
    text-decoration: none;
    color: #007bff;
    border: 1px solid #007bff;
    border-radius: 3px;
    transition: background-color 0.3s;
}

#nipTable_paginate a:hover {
    background-color: #007bff;
    color: #fff;
}
a{
    width:100%;
}
</style>
<body>

{% block content %}
<header>
    <div id="logo">
        {% load static %}
        <img src="{% static 'elomoto.eco-logo-final.png' %}" alt="Company Log" id="img">
    </div>

    <div class="registration-form-container" id="rejestracja">
        <h1 class="registration-header">Rejestracja NIP</h1>
        <div class="registration-form">
        {% if registration_form.is_bound %}
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        {% endif %}

        <a href="{% url 'register_nip' %}" class="registration-form"><button class="registration-button">Zarejestruj Nip</button></a>
        </div>
    </div>


    {% if user.is_authenticated %}
        <div>
            <h3> {{ user.first_name }} {{ user.last_name }}</h3>
        </div>
        <a href="{% url 'logout' %}" class="logout-button">Wyloguj się</a>
    {% endif %}
</header>
    <div id="lista">
        <h1>Twoje rezerwacje</h1>

        <div class="dataTableWrapper">
            <table id="nipTable">
                <thead>
                    <tr>
                        <th>Numer NIP</th>
                        <th>Nazwa firmy</th>
                        <th>Numer telefonu</th>
                        <th>Status rezerwacji</th>
                        <th>Ważny do</th>
                    </tr>
                </thead>
                <tbody>
                    {% for nip in user_nips %}
                    <tr>
                        <td>{{ nip.nip }}</td>
                        <td>{{ nip.nazwa }}</td>
                        <td>{{ nip.numer_telefonu_klienta }}</td>
                        <td>{{ nip.status }}</td>
                        <td>{{ nip.data_koncowa }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    {% endblock %}

    <script>
        $(document).ready(function () {
            $('#nipTable').DataTable({
                "lengthMenu": [25, 50, 100], // Entries dropdown options excluding 10
                "pageLength": 50, // Default number of entries
                "dom": 'lfrtip', // Display only length changing and information elements
                "language": {
                    "url": "https://cdn.datatables.net/plug-ins/1.11.5/i18n/Polish.json"
                }
            });

            // Add a search bar with label
            $('.dataTables_filter input').attr("placeholder", "Search");
        });
    </script>
</body>
</html>